/*

const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const DataSchema = new Schema({

    sid:{
        type:String,
        required:false
      },
      olsubject1:{
          type:String,
          required:false
       },
       olresult1:{
          type:String,
          required:false
       },
       olsubject2:{
          type:String,
          required:false
       },
       olresult2:{
          type:String,
          required:false
       },
       olsubject3:{
          type:String,
          required:false
       },
       olresult3:{
          type:String,
          required:false
       },
       olsubject4:{
          type:String,
          required:false
       },
       olresult4:{
          type:String,
          required:false
       },
       olsubject5:{
          type:String,
          required:false
       },
       olresult5:{
          type:String,
          required:false
       },
       olsubject6:{
          type:String,
          required:false
       },
       olresult6:{
          type:String,
          required:false
       },
       olsubject7:{
          type:String,
          required:false
       },
       olresult7:{
          type:String,
          required:false
       },
       olsubject8:{
          type:String,
          required:false
       },
       olresult8:{
          type:String,
          required:false
       },
       olsubject9:{
          type:String,
          required:false
       },
       olresult9:{
          type:String,
          required:false
       },
       olsubject10:{
          type:String,
          required:false
       },
       olresult10:{
          type:String,
          required:false
       },
       alsubject1:{
          type:String,
          required:false
       },
       alresult1:{
          type:String,
          required:false
       },
       alsubject2:{
          type:String,
          required:false
       },
       alresult2:{
          type:String,
          required:false
       },
       alsubject3:{
          type:String,
          required:false
       },
       alresult3:{
          type:String,
          required:false
       },
       alsubject4:{
          type:String,
          required:false
       },
       alresult4:{
          type:String,
          required:false
       },
       alsubject5:{
          type:String,
          required:false
       },
       alresult5:{
          type:String,
          required:false
       },
       unisubject1:{
          type:String,
          required:false
       },
       uniresult1:{
          type:String,
          required:false
       },
       unisubject2:{
          type:String,
          required:false
       },
       uniresult2:{
          type:String,
          required:false
       },
       unisubject3:{
          type:String,
          required:false
       },
       uniresult3:{
          type:String,
          required:false
       },
       unisubject4:{
          type:String,
          required:false
       },
       uniresult4:{
          type:String,
          required:false
       },
       olschool:{
        type:String,
        required:false
        },
     alschool:{
        type:String,
        required:false
        },
        sclershipschool:{
        type:String,
        required:false
     },
     olindex:{
        type:String,
        required:false
     },
     alindex:{
        type:String,
        required:false
     },
     sclershipindex:{
        type:String,
        required:false
     },
     uniname:{
        type:String,
        required:false
     },
     degreename:{
        type:String,
        required:false
     },
     degreeclass:{
        type:String,
        required:false
     },
     fullname:{
        type:String,
        required:false
     },
     nic:{
        type:String,
        required:false
     },
     gender:{
        type:String,
        required:false
     },
     bod:{
        type:String,
        required:false
     }
       
      
      });

const Data = mongoose.model("Data",dataSchema);

module.exports = Data;

*/